---
ocm-token: eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2NTc2MzU1MDUsImp0aSI6IjU5NTI3OWY4LWZmMGYtNGEwYi1iY2U3LWZjYjNlM2MwODE3YyIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpyaC1lZS1zYWhzaGFoIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImNsb3VkLXNlcnZpY2VzIiwibm9uY2UiOiI4YmE3NTJjYy0wNzVmLTRkZGEtODgyNC1hYWJjMTFmOWNlMDkiLCJzZXNzaW9uX3N0YXRlIjoiZjNkNmY4YmMtNjc4Ny00OWQ0LWFlMzEtOTY4NTIzMWI2NmNmIiwic2NvcGUiOiJvcGVuaWQgYXBpLmlhbS5zZXJ2aWNlX2FjY291bnRzIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiZjNkNmY4YmMtNjc4Ny00OWQ0LWFlMzEtOTY4NTIzMWI2NmNmIn0.fAxhGEZygXIqsNDuj-DYxu6Iap4EIPU6N5YVUfBfxUo     
ocm-token-url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
gateway-url: https://api.integration.openshift.com      
aws:
  - region: "us-east-1"
    access-key: "AKIAWBVQ7Y3UYBMZZBOG"
    secret-access-key: "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"
    account-id: "415909267177"
elastic:
  server: "https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com"
# user: "elastic"
# password: "password"
  index: "test_sahil"
  insecure-skip-verify: true
duration: 1
cooldown: 10
output-path: "/home/sahshah/Desktop/Task1/results"
rate: "60/s"
# test-id: new-test-sahil
tests:
  certificates:
    rate: "60/s"
    duration: 1
