{
 "title": "ocm-api-data",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Datasource", "label": "Datasource", "query": "elasticsearch" },
   {
    "name": "uuid",
    "label": "uuid",
    "query": "{\"find\": \"terms\", \"field\": \"uuid.keyword\"}"
   },
   {
    "name": "error",
    "label": "error",
    "query": "{\"find\": \"terms\", \"field\": \"has_error.keyword\"}"
   },
   {
    "name": "code",
    "label": "code",
    "query": "{\"find\": \"terms\", \"field\": \"code\"}"
   },
   {
    "name": "attack",
    "label": "attack",
    "query": "{\"find\": \"terms\", \"field\": \"attack.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Error vs Non Error Count",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "has_error.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "attack.keyword: $attack AND uuid.keyword: $uuid",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "P99 Percent Change",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      },
      {
       "field": "uuid.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: $attack AND uuid.keyword: $uuid",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Latencies HeatMap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Latencies",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "latency",
       "id": "1",
       "settings": {
        "percents": [
         "25",
         "50",
         "75",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "attack.keyword: $attack",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "latency",
       "id": "1",
       "settings": {
        "percents": [
         "25",
         "50",
         "75",
         "95",
         "99"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "attack.keyword: $attack",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Endpoints P99 latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "resource-review",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: resource-review AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "get-current-account",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: get-current-account AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "self-terms-review",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: self-terms-review AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "cluster-authorizations",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: cluster-authorizations AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "access-review ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: access-review AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "create-cluster",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: create-cluster AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "list-subscriptions",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: list-subscriptions AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "list-clusters",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: list-clusters AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "register-existing-cluster",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: register-existing-cluster AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "quota-cost",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: quota-cost AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "self-access-token",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: self-access-token AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "register-new-cluster",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: register-new-cluster AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Endpoint",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "attack.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "certificates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uuid.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[99.0]", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "latency", "id": "1", "settings": { "percents": [ "99" ] }, "type": "percentiles" }
     ],
     "query": "attack.keyword: certificates AND uuid.keyword: $uuid AND has_error.keyword: $error",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Count of Status Codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Status Code Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 72 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "code",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "has_error.keyword: $error AND attack.keyword: $attack",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}