on: [push, pull_request]
name: CI
jobs:
  go-ci:
    name: GO checks
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -v ./...
      - name: build
        run: make build
      - name: test
        run: ./build/ocm-load-test version
  python-ci:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"
          path: "automation.py ./hack/restructure_file.py ./hack/ES_Upload.py"
