on: [push, pull_request]
name: CI
jobs:
  go-ci:
    name: GO checks
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -v ./...
      - name: build
        run: make build
      - name: test
        run: ./build/ocm-load-test version
  python-ci:
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          path: "automation.py"
